fname: 10d_40in_2ax_route
df_name: df_5s_avg.pickle
dm:
  _name: MyDataModule
  batch_size: 64
dataset:
  _name: RouteDatasetWithRoute
  n_of_route: 10000
  is_2ax: true
  add_noise: false
  divide: 2
  comp: 10
model:
  _name: TransformerDirect
  input_size: 40
  d_model: 40
  nhead: 4
  out_length: 20
  opt_lr: 0.001
route:
  _name: DistanceRotateRouteGeneraterV1
  angle_max: 90
  angle_min: 0
  dist_max: 5
  dist_min: 1
  path_length: 10
  x_range: 30
  y_range: 100
