fname: dec_2ax_route_diff
df_name: df_5s_avg.pickle
dm:
  _name: MyDataModule
  batch_size: 64
dataset:
  _name: RouteDatasetWithRouteDiff
  n_of_route: 10000
  is_2ax: true
  diff_size: 0.13
  add_noise: false
model:
  _name: TransformerWithRouteDecoder
  input_size: 80
  d_model: 80
  nhead: 8
  out_length: 40
  opt_lr: 0.001
route:
  _name: DistanceRotateRouteGeneraterV1
  angle_max: 90
  angle_min: 0
  dist_max: 5
  dist_min: 1
  path_length: 20
  x_range: 30
  y_range: 100
