dataset:
  _name: RouteDatasetWithRoute
  add_noise: false
  is_2ax: true
  n_of_route: 10000
dm:
  _name: MyDataModule
  batch_size: 64
fname: 10d_2ax_route_test
model:
  _name: TransformerDirect
  d_model: 40
  input_size: 40
  nhead: 4
  num_layers: 2
  opt_lr: 0.001
  out_length: 20
route:
  _name: DistanceRotateRouteGeneraterV1
  angle_max: 90
  angle_min: 0
  dist_max: 5
  dist_min: 1
  path_length: 10
  x_range: 30
  y_range: 100
