dataset:
  _name: RouteDatasetWithRoute
  add_noise: false
  comp: -1
  divide: 1
  is_2ax: true
  n_of_route: 10000
df_name: df_5s_avg_hide_harf.pickle
dm:
  _name: MyDataModule
  batch_size: 64
fname: dummy_spot_pos
model:
  _name: TransformerWithRoute
  d_model: 64
  input_size: 4
  nhead: 8
  num_layers: 2
  opt_lr: 0.001
  out_length: 20
route:
  _name: DistanceRotateRouteGeneraterV1
  angle_max: 90
  angle_min: 0
  dist_max: 5
  dist_min: 1
  path_length: 10
  x_range: 30
  y_range: 100
