dm:
  _name: MyDataModule
  batch_size: 64
  n_of_route: 10000
fname: mag-dist
model:
  _name: TransformerByPL
  d_model: 64
  nhead: 8
  num_layers: 2
  use_distance: true
route:
  _name: DistanceRotateRouteGeneraterV1
  angle_max: 90
  angle_min: 0
  dist_max: 5
  dist_min: 1
  path_length: 40
  x_range: 30
  y_range: 100
